// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Home(props) {
  return JsxRuntime.jsx("div", {
              children: "Hello, World!",
              className: "font-semibold dark:text-white"
            });
}

var make = Home;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
