// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Home(Props) {
  return React.createElement("div", {
              className: "font-semibold dark:text-white"
            }, "Hello, World!");
}

var make = Home;

export {
  make ,
}
/* react Not a pure module */
