// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.js";
import * as React from "react";
import * as ReactDom from "react-dom";
import * as Pervasives from "../node_modules/rescript/lib/es6/pervasives.js";

import './main.css'
;

var root = document.querySelector("#root");

if (root == null) {
  Pervasives.failwith("DOM root is missing");
} else {
  ReactDom.render(React.createElement(App.make, {}), root);
}

export {
  
}
/*  Not a pure module */
