// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.js";
import * as React from "react";
import * as PervasivesU from "../node_modules/rescript/lib/es6/pervasivesU.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

import './main.css'
;

var root = document.querySelector("#root");

if (root == null) {
  PervasivesU.failwith("DOM root is missing");
} else {
  var root$1 = Client.createRoot(root);
  root$1.render(JsxRuntime.jsx(React.StrictMode, {
            children: JsxRuntime.jsx(App.make, {})
          }));
}

export {
  
}
/*  Not a pure module */
